### PR TITLE
Restrict ?rankup command to channel #bot-playground

### LINKED ISSUE #26: Restrict ?rankup command to channel #bot-playground
The ?rankup command added in recent times (thanks @Kacarott !) has gained massive popularity within the Codewars Discord server and is invoked very often. However, doing so sometimes drowns various topic channels with noise, detracting from whatever conversation was happening beforehand. As a result, a dedicated channel #bot-playground was created for the purpose of invoking this command (and possibly other future popular recreational commands), though moderators still have to constantly [remind newcomers to move over to that channel for invoking the command](https://discord.com/channels/846624424199061524/846953079710023699/935966514459332618).

Perhaps instead of manual moderation, the ?rankup command itself should only work in #bot-playground ? It would still be helpful to print an informative message in other channels though, so it doesn't give the false impression that the bot is broken or not responding.

### PR DESCRIPTION
**Pull request by DonaldKellett**
Fixes #26

### CODE REVIEW

**Comment by hobovsky** [comment]
I have _totally_ no idea about what it's all about, but this post and related exchange could be relevant: https://github.com/codewars/discord-bot/pull/15#discussion_r781483276

I am sorry if it's not, I have totally no idea what I am talking about.

**Comment by DonaldKellett** [comment]
> I have _totally_ no idea about what it's all about, but this post and related exchange could be relevant: [#15 (comment)](https://github.com/codewars/discord-bot/pull/15#discussion_r781483276)
> 
> I am sorry if it's not, I have totally no idea what I am talking about.

Pretty sure it's relevant, well spotted.

TBH not sure what should be done to prevent this. Should I be using an older Node.js version (currently set to 16)?

**Comment by Kacarott** [comment]
Yes npm v6 is required. Which brings the question, shouldnt we update to a newer npm anway? Perhaps there is a reason to stay on 6, that I am unaware of.

**Comment by kazk** [comment]
As I wrote somewhere, the lockfile should be updated in a separate PR and NPM should be restricted to v7+ to prevent the same problem when v6 is used.

I'll open a PR soon.

**Comment by kazk** [comment]
This is annoying. NPM v6 still runs and updates the lock file even after setting `"engines": {"npm": ">= 7"}`. I'll just update to lockfile v2 for now.

**Review by kazk — CHANGES_REQUESTED** [review]
Please revert the changes to `package-lock.json`.

**Comment by DonaldKellett** [comment]
Seems like I resolved the merge conflict. Or should I just copy the package-lock.json over from `main` and call it a day?

**Comment by DonaldKellett** [comment]
Crap, I think I messed up. I'll open a new pull request shortly.

**Pull request closed without merging**
